# Reusable vars
x-var:
  - &POSTGRES_USER postgres
  - &POSTGRES_PASSWORD default
  - &POSTGRES_DATABASE postgres
  - &node-image node:22

# Reusable envars for postgres
x-postgres-vars: &postgres-vars
  POSTGRES_HOST: database
  POSTGRES_USER: *POSTGRES_USER
  POSTGRES_PASSWORD: *POSTGRES_PASSWORD
  POSTGRES_DATABASE: *POSTGRES_DATABASE

services:
  database:
    image: postgis/postgis:17-3.4 # if using crunchy , make sure to align with crunchy version, currently it is at 16 and postgis 3.3
    container_name: database
    environment:
      <<: *postgres-vars
    healthcheck:
      test: ["CMD", "pg_isready", "-U", *POSTGRES_USER]
    ports: ["5432:5432"]

  migrations:
    image: flyway/flyway:12-alpine
    container_name: migrations
    command: info migrate info
    volumes: ["./migrations/sql:/flyway/sql:ro"]
    environment:
      FLYWAY_URL: jdbc:postgresql://database:5432/postgres
      FLYWAY_USER: *POSTGRES_USER
      FLYWAY_PASSWORD: *POSTGRES_PASSWORD
      FLYWAY_BASELINE_ON_MIGRATE: true
      FLYWAY_DEFAULT_SCHEMA: widgets
    depends_on:
      database:
        condition: service_healthy

  schemaspy:
    image: schemaspy/schemaspy:7.0.2
    profiles: ["schemaspy"]
    container_name: schemaspy
    command: -t pgsql11 -db postgres -host database -port 5432 -u postgres -p default -schemas widgets
    depends_on:
      migrations:
        condition: service_completed_successfully
    volumes: ["./output:/output"]

  backend:
    container_name: backend
    depends_on:
      migrations:
        condition: service_started
    entrypoint: sh -c "npm i && npm run start:dev"
    environment:
      <<: *postgres-vars
      NODE_ENV: development
      OIDC_AUTHORITY: ${OIDC_AUTHORITY:-}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-widget-ui-sdx-reference-implementation-21920}
      OIDC_OPENID_CONNECT_URL: ${OIDC_OPENID_CONNECT_URL:-}
      SWAGGER_OAUTH_CLIENT_ID: ${SWAGGER_OAUTH_CLIENT_ID:-}
      SWAGGER_OAUTH_REDIRECT_URL: ${SWAGGER_OAUTH_REDIRECT_URL:-http://localhost:3001/api/docs/oauth2-redirect.html}
      SWAGGER_OAUTH_SCOPES: ${SWAGGER_OAUTH_SCOPES:-${OIDC_SCOPE:-openid profile nrs:widgets:read nrs:widgets:create nrs:widgets:update nrs:widgets:delete nrs:widgets:admin}}
    image: *node-image
    ports: ["3001:3000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api"]
    working_dir: "/app"
    volumes:
      - "./backend:/app"
      - "/app/node_modules"
      - "/app/src/generated"
      - "/app/dist"

  frontend:
    container_name: frontend
    entrypoint: sh -c "npm ci --ignore-scripts && npm run dev"
    environment:
      API_BASE_URL: ${API_BASE_URL:-http://localhost:3001/api/v1}
      OIDC_AUTHORITY: ${OIDC_AUTHORITY:-}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-widget-ui-sdx-reference-implementation-21920}
      OIDC_DISPLAY_NAME_CLAIM: ${OIDC_DISPLAY_NAME_CLAIM:-name}
      OIDC_POST_LOGOUT_REDIRECT_URI: ${OIDC_POST_LOGOUT_REDIRECT_URI:-}
      OIDC_REDIRECT_URI: ${OIDC_REDIRECT_URI:-}
      OIDC_SCOPE: ${OIDC_SCOPE:-openid profile nrs:widgets:read nrs:widgets:create nrs:widgets:update nrs:widgets:delete nrs:widgets:admin}
      OIDC_SILENT_REDIRECT_URI: ${OIDC_SILENT_REDIRECT_URI:-}
      PORT: 3000
      NODE_ENV: development
    image: *node-image
    ports: ["3000:3000"]
    volumes: ["./frontend:/app", "/app/node_modules"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    working_dir: "/app"
    depends_on:
      backend:
        condition: service_healthy

  caddy:
    container_name: caddy
    profiles: ["caddy"]
    build: ./frontend
    environment:
      NODE_ENV: development
      PORT: 3000
      API_BASE_URL: ${API_BASE_URL:-http://localhost:3001/api/v1}
      LOG_LEVEL: info
      OIDC_AUTHORITY: ${OIDC_AUTHORITY:-}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-widget-ui-sdx-reference-implementation-21920}
      OIDC_DISPLAY_NAME_CLAIM: ${OIDC_DISPLAY_NAME_CLAIM:-name}
      OIDC_POST_LOGOUT_REDIRECT_URI: ${OIDC_POST_LOGOUT_REDIRECT_URI:-}
      OIDC_REDIRECT_URI: ${OIDC_REDIRECT_URI:-}
      OIDC_SCOPE: ${OIDC_SCOPE:-openid profile nrs:widgets:read nrs:widgets:create nrs:widgets:update nrs:widgets:delete nrs:widgets:admin}
      OIDC_SILENT_REDIRECT_URI: ${OIDC_SILENT_REDIRECT_URI:-}
    ports: ["3005:3000"]
    volumes: ["./frontend/Caddyfile:/etc/caddy/Caddyfile"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    depends_on:
      backend:
        condition: service_healthy
