import { ApiProperty, ApiSchema } from '@nestjs/swagger'

export const SDX_WIDGET_STATUSES = ['active', 'inactive', 'archived'] as const
export type SdxWidgetStatus = (typeof SDX_WIDGET_STATUSES)[number]

export const SDX_WIDGET_EXAMPLE = {
  id: '4f3066e8-5a59-4fc5-8e7b-fcd7f4d01c4f',
  subject: 'user-123',
  name: 'Intake form',
  description: 'Widget used for intake workflow testing.',
  status: 'active',
  metadata: {
    source: 'local-dev',
  },
  createdAt: '2026-05-13T18:00:00Z',
  updatedAt: '2026-05-13T18:00:00Z',
}

@ApiSchema({ name: 'SdxWidget' })
export class SdxWidgetDto {
  @ApiProperty({
    format: 'uuid',
    example: SDX_WIDGET_EXAMPLE.id,
    readOnly: true,
  })
  id: string

  @ApiProperty({
    description: 'Owner subject from the JWT sub claim or admin operation.',
    example: SDX_WIDGET_EXAMPLE.subject,
    readOnly: true,
  })
  subject: string

  @ApiProperty({
    minLength: 1,
    maxLength: 200,
    example: SDX_WIDGET_EXAMPLE.name,
  })
  name: string

  @ApiProperty({
    nullable: true,
    maxLength: 1000,
    example: SDX_WIDGET_EXAMPLE.description,
  })
  description: string | null

  @ApiProperty({
    enum: SDX_WIDGET_STATUSES,
    example: SDX_WIDGET_EXAMPLE.status,
  })
  status: SdxWidgetStatus

  @ApiProperty({
    type: 'object',
    additionalProperties: true,
    example: SDX_WIDGET_EXAMPLE.metadata,
  })
  metadata: Record<string, unknown>

  @ApiProperty({
    format: 'date-time',
    example: SDX_WIDGET_EXAMPLE.createdAt,
    readOnly: true,
  })
  createdAt: Date

  @ApiProperty({
    format: 'date-time',
    example: SDX_WIDGET_EXAMPLE.updatedAt,
    readOnly: true,
  })
  updatedAt: Date
}

@ApiSchema({ name: 'ErrorResponse' })
export class ErrorResponseDto {
  @ApiProperty({
    description: 'A short, machine-readable error code or identifier.',
    example: 'forbidden',
  })
  error: string

  @ApiProperty({
    description: 'A human-readable summary of the error.',
    example: 'You are not authorized to access this resource',
  })
  message: string

  @ApiProperty({
    required: false,
    nullable: true,
    type: Object,
    additionalProperties: true,
    description:
      'Optional error context. Generated error responses include a correlationId for support and log tracing. Values generated by this API use the sdxw-<uuid> format; inbound x-request-id or x-correlation-id values are preserved as received.',
    example: {
      correlationId: 'sdxw-2f7b8d43-7b0d-4b5f-8a6c-1a2b3c4d5e6f',
      timestamp: '2026-01-16T19:22:00Z',
    },
  })
  details?: Record<string, unknown> | null
}

@ApiSchema({ name: 'ProblemDetailErrorItem' })
export class ProblemDetailErrorItemDto {
  @ApiProperty({
    enum: ['body', 'query', 'header', 'path', 'cookie'],
    example: 'body',
  })
  location: 'body' | 'query' | 'header' | 'path' | 'cookie'

  @ApiProperty({
    example: 'INVALID_REQUEST',
  })
  code: string

  @ApiProperty({
    example: 'Invalid request body or parameter',
  })
  message: string

  @ApiProperty({
    example: 'tag:validation-error',
  })
  type: string

  @ApiProperty({
    required: false,
    nullable: true,
    example: 'name',
  })
  field?: string | null

  @ApiProperty({
    required: false,
    nullable: true,
    example: 'name must be a non-empty string up to 200 characters',
  })
  detail?: string | null

  @ApiProperty({
    required: false,
    nullable: true,
    example: '',
  })
  received?: string | null

  @ApiProperty({
    required: false,
    nullable: true,
    example: '#/name',
  })
  pointer?: string | null

  @ApiProperty({
    required: false,
    nullable: true,
    type: Object,
    additionalProperties: true,
    example: {
      minLength: 1,
      maxLength: 200,
    },
  })
  constraints?: Record<string, unknown> | null
}

@ApiSchema({ name: 'ProblemDetailResponse' })
export class ProblemDetailResponseDto {
  @ApiProperty({
    example: 'tag:validation-errors',
  })
  type: string

  @ApiProperty({
    example: 'Bad Request',
  })
  title: string

  @ApiProperty({
    example: 400,
  })
  status: number

  @ApiProperty({
    required: false,
    nullable: true,
    example: 'One or more validation errors occurred',
  })
  detail?: string | null

  @ApiProperty({
    type: ProblemDetailErrorItemDto,
    isArray: true,
    minItems: 1,
  })
  errors: ProblemDetailErrorItemDto[]
}
